version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitTestProject
  gitServerName: GitExt
  gitUrl: https://github.com/aadi-tripathi
  gitUsername: aadi-tripathi
  gitBranch: release/2.0.0
services:
- serviceName: project.gittest.integrations:daf_1
  packages:
  - name: GitTestProject
    version: 2.0.0
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.1028
